version: "3.8"

services:
  # 1. RTSP 서버 (MediaMTX)
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    network_mode: host
    restart: always

  # 2. GStreamer 송출기 (미리 빌드된 이미지 사용)
  gst-publisher:
    build: .
    container_name: gst-publisher
    image: rtsp_streaming-gst-publisher:latest
    network_mode: host
    runtime: nvidia
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/nvhost-vic:/dev/nvhost-vic"
      - "/dev/nvhost-gpu:/dev/nvhost-gpu"
      - "/dev/nvhost-ctrl-gpu:/dev/nvhost-ctrl-gpu"
      - "/dev/nvargus-daemon:/dev/nvargus-daemon" # CSI 카메라 필수
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket # 카메라 데몬 소켓 공유
    stdin_open: true
    tty: true
    restart: always